name: Terraform CI

on:
  [workflow_dispatch]

jobs:
  terraform:
    runs-on: [self-hosted]

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 3: Install Infracost
      - name: Install Infracost
        run: |
          curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz -o infracost.tar.gz
          tar -xzvf infracost.tar.gz -C /usr/local/bin
          
      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Run Infracost to get cost estimation
      - name: Infracost Estimate
        run: |
          infracost breakdown --path=tfplan --format=json > infracost-output.json
          
      # Step 8: Upload Infracost output as an artifact (Optional)
      - name: Upload Infracost Output
        uses: actions/upload-artifact@v3
        with:
          name: infracost-output
          path: infracost-output.json
          
      # Step 9: Display Infracost results in the logs
      - name: Display Infracost output
        run: cat infracost-output.json
