name: Terraform CI

on:
  [workflow_dispatch]

jobs:
  terraform:
    runs-on: [self-hosted]

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v  # Verify node installation

      # Step 3: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 4: Install Infracost
      - name: Install Infracost
        run: |
          curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz -o infracost.tar.gz
          # Extract Infracost to a directory where the runner has write permissions
          tar -xzvf infracost.tar.gz -C /tmp
          # Move Infracost binary to /usr/local/bin
          sudo mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
          sudo chmod +x /usr/local/bin/infracost
          
      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 8: Run Infracost to get cost estimation
      - name: Infracost Estimate
        run: |
          infracost breakdown --path=tfplan --format=json > infracost-output.json
          
      # Step 9: Upload Infracost output as an artifact (Optional)
      - name: Upload Infracost Output
        uses: actions/upload-artifact@v3
        with:
          name: infracost-output
          path: infracost-output.json
          
      # Step 10: Display Infracost results in the logs
      - name: Display Infracost output
        run: cat infracost-output.json

        