name: Terraform CI with Infracost

on:
  [workflow_dispatch]

jobs:
  terraform:
    runs-on: [self-hosted]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js (Red Hat-based systems)
      - name: Install Node.js (Red Hat)
        run: |
          sudo yum clean all
          sudo yum install -y gnupg
          curl -sL https://rpm.nodesource.com/gpgkey/NODESOURCE-GPG-SIGNING-KEY-EL | sudo tee /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
          curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
          sudo yum install -y nodejs
          node -v  # Verify Node.js installation

      # Step 3: Install Infracost
      - name: Install Infracost
        run: |
          curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz -o infracost.tar.gz
          tar -xvzf infracost.tar.gz
          sudo mv infracost-linux-amd64 /usr/local/bin/infracost
          infracost --version  # Verify Infracost installation

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Run Infracost for cost estimation
      - name: Run Infracost
        run: |
          infracost breakdown --path=./ --format=json > infracost_output.json
          cat infracost_output.json
