name: Terraform CI with Infracost

on:
  [workflow_dispatch]

jobs:
  terraform:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if required for Infracost)
        run: |
          if ! command -v node &> /dev/null; then
            curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Run Infracost for Cost Estimation
        run: |
          # Assuming terraform plan file is created with -out=tfplan
          infracost breakdown --path=tfplan --format=json > infracost_output.json

      - name: Upload Infracost Report
        uses: actions/upload-artifact@v3
        with:
          name: infracost-report
          path: infracost_output.json
